# -*- coding: utf-8 -*-
"""dashboard_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1civOsauhcIDI1h3NS17pCQ1Cw3Tup5Pg
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="Dashboard Interativo", layout="wide")

@st.cache_data
def carregar_dados():
    return sns.load_dataset("tips")

df = carregar_dados()

st.title("💰 Dashboard Interativo - Gorjetas")

# Filtros
st.sidebar.header("Filtros")
sexo = st.sidebar.selectbox("Sexo", options=["Todos"] + list(df['sex'].unique()))
dias = st.sidebar.multiselect("Dia da Semana", options=df['day'].unique(), default=df['day'].unique())

df_filtrado = df.copy()

if sexo != "Todos":
    df_filtrado = df_filtrado[df_filtrado["sex"] == sexo]
if dias:
    df_filtrado = df_filtrado[df_filtrado["day"].isin(dias)]

# Métricas
st.subheader("📊 Métricas")
col1, col2, col3 = st.columns(3)
col1.metric("Total de Registros", len(df_filtrado))
col2.metric("Gorjeta Média", f"${df_filtrado['tip'].mean():.2f}")
col3.metric("Total Faturado", f"${df_filtrado['total_bill'].sum():.2f}")

# Gráfico
st.subheader("📈 Distribuição das Gorjetas")
fig, ax = plt.subplots()
sns.boxplot(data=df_filtrado, x="day", y="tip", hue="sex", ax=ax)
st.pyplot(fig)

# Tabela
st.subheader("🧾 Dados")
st.dataframe(df_filtrado)
